import { NextResponse } from "next/server";
import { z } from "zod";
import type { Prisma } from "@prisma/client";
import { requireAdmin } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";
const schema=z.object({weekId:z.string().cuid(),taskId:z.string().cuid(),position:z.number().int().min(0).optional()});
const reorderSchema=z.object({id:z.string().cuid(),position:z.number().int().min(0),published:z.boolean().optional()});
export async function GET(request:Request){try{await requireAdmin();const weekId=new URL(request.url).searchParams.get("weekId");if(!weekId)return NextResponse.json({error:"Укажите weekId"},{status:400});return NextResponse.json(await prisma.weekTask.findMany({where:{weekId},orderBy:[{position:"asc"},{id:"asc"}]}))}catch{return NextResponse.json({error:"Доступ запрещён"},{status:403})}}
export async function POST(request:Request){try{const admin=await requireAdmin();const data=schema.parse(await request.json());const [task,week]=await Promise.all([prisma.task.findUnique({where:{id:data.taskId}}),prisma.marathonWeek.findUnique({where:{id:data.weekId}})]);if(!task||!week)return NextResponse.json({error:"Неделя или задание не найдены"},{status:404});const position=data.position??await prisma.weekTask.count({where:{weekId:week.id}});const item=await prisma.weekTask.create({data:{weekId:week.id,taskId:task.id,titleSnapshot:task.title,descriptionSnapshot:task.description,locationSnapshot:task.location,xpSnapshot:task.xp,allowedDaysSnapshot:(task.allowedDays??[]) as Prisma.InputJsonValue,maxCompletionsSnapshot:task.maxCompletions,position}});await prisma.adminAuditLog.create({data:{actorId:admin.id,action:"ASSIGN",entityType:"WeekTask",entityId:item.id,details:{weekId:week.id,taskId:task.id}}});return NextResponse.json(item,{status:201})}catch{return NextResponse.json({error:"Не удалось назначить задание"},{status:400})}}
export async function DELETE(request:Request){try{const admin=await requireAdmin();const id=new URL(request.url).searchParams.get("id");if(!id)return NextResponse.json({error:"Укажите id"},{status:400});const progress=await prisma.characterTaskProgress.count({where:{weekTaskId:id}});if(progress)return NextResponse.json({error:"Нельзя убрать задание с прогрессом игроков"},{status:409});await prisma.weekTask.delete({where:{id}});await prisma.adminAuditLog.create({data:{actorId:admin.id,action:"UNASSIGN",entityType:"WeekTask",entityId:id}});return new NextResponse(null,{status:204})}catch{return NextResponse.json({error:"Не удалось убрать задание"},{status:400})}}
export async function PATCH(request:Request){try{const admin=await requireAdmin(),data=reorderSchema.parse(await request.json());const item=await prisma.weekTask.update({where:{id:data.id},data:{position:data.position,published:data.published}});await prisma.adminAuditLog.create({data:{actorId:admin.id,action:"UPDATE",entityType:"WeekTask",entityId:item.id,details:data}});return NextResponse.json(item)}catch{return NextResponse.json({error:"Не удалось изменить назначение"},{status:400})}}
